### ISSUE TITLE
Multi-lingual support for MyFursona

### ISSUE THREAD

**Issue by kuroji-fusky** [MyArtverse-Project/MyArtverse#36]
In an effort to make the platform accessible to everyone, multi-lingual support is necessary; currently, assigned to those onboard already:

- __Filipino__ - @kuroji-fusky 
- __Indonesian__ - @thatITfox
- __German__ = @MCWertGaming
- __Spanish__ - @VulpoTheDev

**Comment by staxfur** [comment]
Are there plans already on how we want to setup Translations?

**Comment by ghost** [comment]
We'll use [CrowdIn](https://crowdin.com) for this since it accepts JSON files and they'll fill in the necessary translations
